---
- hosts: all
  vars:
    # conda: true
    RUNNER_VERSION: 2.160.2
  vars_prompt:
    - name: "ORG"
      prompt: "What is the GitHub organization?"
    - name: "REPO"
      prompt: "What is the GitHub repository?"
    - name: "GITHUB_ACTIONS_TOKEN"
      prompt: "Please enter the GitHub Actions token for this workflow"
  remote_user: tester
  become: no
  tasks:

    - name: Showing the input variables
      debug:
        msg: "Setting up a GitHub runner for repository: https://github.com/{{ ORG }}/{{ REPO }}"

    - name: Create a directory for the runner
      file:
        path: /tmp/actions_runner
        state: directory

    - name: Download and extract the runner
      unarchive:
        src: https://githubassets.azureedge.net/runners/{{ RUNNER_VERSION }}/actions-runner-linux-x64-{{ RUNNER_VERSION }}.tar.gz
        dest: /tmp/actions_runner/
        creates: /tmp/actions_runner/config.sh
        remote_src: yes

    - name: Configure GitHub Action runner
      command: chdir=/tmp/actions_runner ./config.sh --url https://github.com/{{ ORG }}/{{ REPO }} --token '{{ GITHUB_ACTIONS_TOKEN }}'

    - name: run it
      shell: /tmp/actions_runner/run.sh &
